name: Dependency Update

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Compile updated requirements
        run: pip-compile --upgrade

      - name: Commit and push updates
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add requirements.txt
          git commit -m "Update dependencies"
          git push
          
